apiVersion: v1
kind: Service
metadata:
  name: koorde-cache-http
  namespace: koorde-cache
  labels:
    app: koorde-node
spec:
  type: NodePort
  selector:
    app: koorde-node
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30080
    protocol: TCP

