apiVersion: v1
kind: Service
metadata:
  name: dht-headless
  labels:
    app: dht-node
spec:
  clusterIP: None
  selector:
    app: dht-node
  ports:
  - name: grpc
    port: 4000
    targetPort: 4000
    protocol: TCP
